### ISSUE TITLE
Build regression updating to 0.5.0

### ISSUE THREAD

**Issue by aeddie-mumbacloud** [Netflix/falcor-router#197]
I got a test regression after updating to 0.5.0. I hope the following is enough information to either help me work out what I'm doing wrong, or help you work out what's going wrong.

Invocation in Mocha test (I'm using a custom class for the router):

```typescript
(new Router(authId))
  .get([['customer', 'stores', { from: 0, to: 9 }, ['id']]])
  .subscribe((result: any) => {
    // console.log(JSON.stringify(values, null, 2));
    assert.equal(result.jsonGraph.customer.storesById['1'].id, 1, 'should be the result');
    done();
}, done);
```

The error is:

```sh
1) index integrations tests should route `getStores`:
     TypeError: Observable.from(...).expand is not a function
      at _recurseMatchAndExecute (node_modules/falcor-router/src/run/recurseMatchAndExecute.js:44:9)
      at recurseMatchAndExecute (node_modules/falcor-router/src/run/recurseMatchAndExecute.js:21:12)
      at DeferSubscriber.factory (node_modules/falcor-router/src/router/get.js:29:16)
      at DeferSubscriber._callFactory (node_modules/rxjs/observable/DeferObservable.js:86:27)
      at DeferSubscriber.tryDefer (node_modules/rxjs/observable/DeferObservable.js:79:18)
      at new DeferSubscriber (node_modules/rxjs/observable/DeferObservable.js:75:14)
      at DeferObservable._subscribe (node_modules/rxjs/observable/DeferObservable.js:65:16)
      at DeferObservable.Observable.subscribe (node_modules/rxjs/Observable.js:45:27)
      at DeferObservable.rxNewObservable.subscribe (node_modules/falcor-router/src/run/conversion/rxNewToRxNewAndOld.js:9:41)
      at Object.<anonymous> (dist/test/src/index.test.js:66:18)
```

In `recurseMatchAndExectue.js:42`, `Observable.from(paths)` is returning an `ArrayObservable` but the `.expand` property is definitely undefined. `paths` is populated.

Thoughts on whether there is something wrong on my end or your end?

**Comment by sdesai** [comment]
@aeddie-mumbacloud thanks for the report.

@jhusain @blesh - can you guys provide some guidance on this when you get a chance given the missing operator (related to the Rx5-to-4 adaptor?)

**Comment by eddieajau** [comment]
Found the problem (sorry, logged in with my work account before).

Need to add the following to `/src/RouterRx.js`:

```javascript
require('rxjs/add/observable/empty');
require('rxjs/add/operator/expand');
require('rxjs/add/operator/reduce');
require('rxjs/add/operator/map');
require('rxjs/add/operator/filter');
```

Now, this is only to make my build tests run so it may not cover all the possible bases. If you can give me some guidance on which test to alter to pick up the error I can have a go at patching that as well.

**Comment by jhusain** [comment]
This breakage is expected, but should have been messaged more clearly with the release. As part of this upgrade we have moved the Router from RX 2 to Rx 5. This means that some of the functions on the Observables emitted from the Router will be renamed. For example, "flatMapLatest" has become "switchMap."

You have two options: you can adapt the Observable returned from the Router into an Rx 2 Observable and leave your code as-is, or you can update your code to use the RX5 API.  My recommendation is that you explicitly adapt the Observable emitted from the Router into the Observable used by whatever library Observable library you are using (ex. Rx 2.0, Rx 5.0, Bacon). The reason I recommend this approach is that in the future it's possible we may remove all the functions from the Observable emitted from the Router (other than subscribe) in order to reduce file size. Explicitly adapting the Observable ensures that you won't be broken by such a change in the future.

**Comment by jhusain** [comment]
If you choose to adapt the output of Router methods back to the old Rx 2.0 Observable API, the following code should work:

~~~js 
var Rx = require("rx");
 function toObservable2(obs ) {
   return Rx.Observable.create (observer => {
     let subscription = obs.subscribe({
      next(value) {
        observer.onNext(value);
      },
      error(e) {
        observer.onError(e);
      },
      complete() {
        observer.onComplete();
      }
    });
    return () =>  subscription.unsubscribe();
  });
}

var oldObservableAPI = toObservable2(router.get([["videos", 278, "name"]]));

// this adapted Observable has the same API as 0.4.0
oldObservableAPI.subscribe ({
  onNext(value) { 
    console.log (value);
  }
});
~~|

**Comment by eddieajau** [comment]
@jhusain I've had a look at this with my other developer who is familiar with RxJS and he's also of the opinion that I'm not doing anything weird. Your monkey-patching file [`/src/RouterRx.js`](https://github.com/Netflix/falcor-router/blob/master/src/RouterRx.js) doesn't appear to be adding the `expand` operator that is being invoked in [`/src/run/recurseMatchAndExecute.js`](https://github.com/Netflix/falcor-router/blob/master/src/run/recurseMatchAndExecute.js#L43).

Also I confirmed in `/src/run/conversion/rxNewToRxNewAndOld.js` that the switch statement is matching on `function`.

**Comment by eddieajau** [comment]
Ok, the reason you are probably not seeing this in the tests is because [`/test/data/VideoRoutes.js`](https://github.com/Netflix/falcor-router/blob/master/test/data/VideoRoutes.js#L1) is loading the full RxJS suite.

**Comment by eddieajau** [comment]
PR submitted. See #200
