### PR TITLE
Fix usage of full Rx object in tests

### LINKED ISSUE #197: Build regression updating to 0.5.0
I got a test regression after updating to 0.5.0. I hope the following is enough information to either help me work out what I'm doing wrong, or help you work out what's going wrong.

Invocation in Mocha test (I'm using a custom class for the router):

```typescript
(new Router(authId))
  .get([['customer', 'stores', { from: 0, to: 9 }, ['id']]])
  .subscribe((result: any) => {
    // console.log(JSON.stringify(values, null, 2));
    assert.equal(result.jsonGraph.customer.storesById['1'].id, 1, 'should be the result');
    done();
}, done);
```

The error is:

```sh
1) index integrations tests should route `getStores`:
     TypeError: Observable.from(...).expand is not a function
      at _recurseMatchAndExecute (node_modules/falcor-router/src/run/recurseMatchAndExecute.js:44:9)
      at recurseMatchAndExecute (node_modules/falcor-router/src/run/recurseMatchAndExecute.js:21:12)
      at DeferSubscriber.factory (node_modules/falcor-router/src/router/get.js:29:16)
      at DeferSubscriber._callFactory (node_modules/rxjs/observable/DeferObservable.js:86:27)
      at DeferSubscriber.tryDefer (node_modules/rxjs/observable/DeferObservable.js:79:18)
      at new DeferSubscriber (node_modules/rxjs/observable/DeferObservable.js:75:14)
      at DeferObservable._subscribe (node_modules/rxjs/observable/DeferObservable.js:65:16)
      at DeferObservable.Observable.subscribe (node_modules/rxjs/Observable.js:45:27)
      at DeferObservable.rxNewObservable.subscribe (node_modules/falcor-router/src/run/conversion/rxNewToRxNewAndOld.js:9:41)
      at Object.<anonymous> (dist/test/src/index.test.js:66:18)
```

In `recurseMatchAndExectue.js:42`, `Observable.from(paths)` is returning an `ArrayObservable` but the `.expand` property is definitely undefined. `paths` is populated.

Thoughts on whether there is something wrong on my end or your end?

### PR DESCRIPTION
**Pull request by eddieajau**
Fixes #197 

Tests are currently using the full Rx object which is not available when using the router in production. This PR ensures all tests use a plain `Observable` (`require('rxjs/Observable').Observable`).

Additional operators and behaviours are added to make tests pass.

### CODE REVIEW

**Comment by blesh** [comment]
@eddieajau this duplicate work to #199. It's also adding one operator that the router doesn't use, only the test does.  I'm going to close this in favor of #199, not because I authored #199, but because the latter forces the tests to use the same version of the router Observable without altering it's prototype, which should give more predictable results in the long run (as long as we're diligent about not letting tests use the full Rx library)

Thank you for your contribution! I appreciate looking through someone else's solution to the problem and I'm very pleased you took the time and effort to look into this.

**Comment by eddieajau** [comment]
No worries. Thanks for the prompt fix :)
